### ISSUE TITLE
Two different VerifiableCredential classes for same datastructure

### ISSUE THREAD

**Issue by jarimayenburg** [reinkrul/java-nuts-client#3]
The library is currently generated with two different classes for VCs, namely `nl.reinkrul.nuts.auth.VerifiableCredential` and `nl.reinkrul.nuts.vcr.v2.VerifiableCredential`. This causes issues when you want to share VC objects between APIs.

This is probably because the spec has this type defined separately in https://github.com/nuts-foundation/nuts-node/blob/master/docs/_static/auth/v1.yaml and https://github.com/nuts-foundation/nuts-node/blob/master/docs/_static/vcr/v2.yaml. Both of those refer to the same common type though (`$ref: '../common/ssi_types.yaml#/components/schemas/VerifiableCredential'`).

Would it be an option to delete the schema definitions for these two types from the spec and just directly refer to the common type where it's used? I'm assuming this happens with more schemas than just VerifiableCredentials.

We're currently trying to see if an ObjectMapper might work as a workaround.

**Comment by jarimayenburg** [comment]
`ObjectMapper` works

**Comment by reinkrul** [comment]
> Both of those refer to the same common type though ($ref: '../common/ssi_types.yaml#/components/schemas/VerifiableCredential').

I think there's work in Nuts-node to have this fixed in the next release, this library will follow. Good to hear using an ObjectMapper works for now 👍

**Comment by reinkrul** [comment]
Just fixed in the latest version (v5.0.0), should be available in Maven central tomorrow.

https://github.com/reinkrul/java-nuts-client/releases/tag/v5.0.0
