### ISSUE TITLE
Generated APIs require a "jwtBearerAuth" token, which seems impossible to set

### ISSUE THREAD

**Issue by jarimayenburg** [reinkrul/java-nuts-client#4]
It seems that the `security` field in the OpenAPI spec causes the generator to require that a `jwtBearerAuth` token is set, but the code to set it isn't generated. This causes any call using an AuthApi client (and possibly other clients that have this securitySchema) to throw an exception.

This is where the exception is thrown (in `nl.reinkrul.nuts.ApiClient`)
```java
    public void updateParamsForAuth(String[] authNames, List<Pair> queryParams, Map<String, String> headerParams,
                                    Map<String, String> cookieParams, String payload, String method, URI uri) throws ApiException {
        for (String authName : authNames) {
            Authentication auth = authentications.get(authName);
            if (auth == null) {
                throw new RuntimeException("Authentication undefined: " + authName);
            }
            auth.applyToParams(queryParams, headerParams, cookieParams, payload, method, uri);
        }
    }
```

The part of the OpenAPI spec that defines this securitySchema
```yaml
  securitySchemes:
    jwtBearerAuth:
      type: http
      scheme: bearer

security:
  - {}
  - jwtBearerAuth: []
```

The part of `AuthApi` that requires this authentication (in `nl.reinkrul.nuts.auth.AuthApi`)
```java
String[] localVarAuthNames = new String[] { "jwtBearerAuth" };
return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
```

You're supposed to be able to set this bearer token in the `ApiClient`, but the setter that's supposed to do that isn't generated and the `authentications` map that's supposed to contain this `jwtBearerAuth` authentication is immediately set to immutable.

In `nl.reinkrul.nuts.ApiClient`
```java
    public ApiClient() {
        init();
        initHttpClient();

        // Setup authentications (key: authentication name, value: authentication).
        // Prevent the authentications from being modified.
        authentications = Collections.unmodifiableMap(authentications);
    }
```

I worked around this issue by deleting the `securitySchema` and `security` fields of the OpenAPI specs

**Comment by reinkrul** [comment]
It is caused because by generating a model-only OpenAPI (which technically isn't supported but works nonetheless, but has no authentication) for shared code as last step, which overwrote the (correctly) earlier generated API client. Moved that higher up and all is fine now. Added tests to assert it's working with both no auth and JWT bearer. Released as v5.0.1
